### ISSUE TITLE
Five point relative pose

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#103]
Did you read this article "An Iterative 5-pt Algorithm for Fast and
Robust Essential Matrix Estimation",  if yes did you make some experements ?

**Comment by sweeneychris** [comment]
Yes, I have seen this article. Since it is an iterative method it requires an initialization and thus is best used for tracking or video SfM. The 5-point algorithm in Theia is the extremely robust method by Stewenius and, in my opinion, is the best method for computing the relative pose under unknown general motion.

I'm very happy to answer these kinds of questions but I feel that the Theia mailing list is a more appropriate place for discussions. The github issues should be for code-related questions and support only.
