### ISSUE TITLE
FOV and Fisheye camera calibration formats

### ISSUE THREAD

**Issue by bugakov** [sweeneychris/TheiaSfM#114]
Hello Chris,
Is there a way to use in your sample build_reconstruction app other camera models than Pinhole?
I used camera calibration tool to get FOV and Fisheye camera intrinsics, but it gives different amount of parameters comparing to pinhole. Are there sample calibration files for those camera models or a description somewhere how to use those models?
Thanks

**Comment by sweeneychris** [comment]
Right now there are no calibration files for those camera formats. I have not had the time to think of a nice calibration format that can handle all camera models. What I have been doing is to manually add in the calibration around this line so that it will be added to each camera properly: https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction.cc#L335

That solution is not the most elegant, but it is simple enough to do until I come up with an ascii calibration file for fisheye and fov formats.
