### ISSUE TITLE
Finding a pair for incremental SfM

### ISSUE THREAD

**Issue by mardy** [sweeneychris/TheiaSfM#142]
Hi Chris!
  I've build theia as a snap package (see https://snapcraft.io for more info), and I'm soon going to propose a branch with the snap recipe. But while I was testing the software, I noticed that I cannot get the incremental SfM to work.
Here are the logs:

http://paste.ubuntu.com/24112658/

Are there any parameters I should tweak, in order to get a better result? By the way, the reconstruction seems fine, but it's rather sparse; do I understand it correctly, that if the incremental SfM were working, I could get a denser reconstruction?

Also, another question: the generated PLY file seems to contain only two colours: do I understand correctly, that black points are those who correspont to a model feature, while green ones correspond to camera poses?

**Comment by sweeneychris** [comment]
Line 4213:
Reconstruction estimation statistics: 
	Num estimated views = 39
	Num input views = 57
	Num estimated tracks = 4189
	Num input tracks = 6548
	Pose estimation time = 0.077339
	Triangulation time = 0.713377
	Bundle Adjustment time = 15.1171
	Total time = 17.1423

Incremental Reconstruction Estimator timings:
	Time to find an initial seed for the reconstruction: 1.20426

It sure seems like it worked :)

Theia will try to generate as many reconstructions as possible from the input data. So once it reaches a point where it cannot reliably add more images to the model, it will try to create a second, independent reconstruction from the remaining images. In this case, Theia wasn't able to find a good initial pair for building that second reconstruction.

The problem here seems to be a lack of feature matches. I would try loosening the matching thresholds (increase lowes ratio) or changing the feature density to DENSE. Both can be changed in the build_reconstruction_flags.txt file.

**Comment by mardy** [comment]
Hi Chris, thanks for your prompt reply! Indeed, the reconstruction I obtained was quite satisfactory, I was just misled by the last lines in the output, which seemed to hint at some problem.

Feel free to close this issue (bonus points if you answer the question about the ply colorization, whether green points are camera poses). :-)

**Comment by sweeneychris** [comment]
Hey sorry I missed that question before! Yes, the green dots are indeed the camera positions in PLY
