### ISSUE TITLE
Provide known camera positions

### ISSUE THREAD

**Issue by Yasmina-AC** [sweeneychris/TheiaSfM#155]
Hello, 

I have some images taken from a drone with known GPS positions. I'd like to use those positions within `TheiaSfm `to get camera rotations, but I don't know where to start. Would it be possible to provide GPS positions to the application `build_reconstruction`? 

Any help on this would be very grateful. Many thanks for this useful library!

**Comment by sweeneychris** [comment]
Right now there is not a good mechanism for using known rotations for the position estimation. But you can use the global sfm pipeline per usual to first get the camera orientations, then modify the nonlinear position estimator slightly to initialize the positions with your GPS. You'll want to change this function to use your GPS priors instead of random initialization:

https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/global_pose_estimation/nonlinear_position_estimator.cc#L165

You can convert lat/lon to ECEF with this class: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/gps_converter.h#L54

I would recommend storing the GPS in the camera intrinsics prior: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/camera_intrinsics_prior.h#L92

**Comment by Yasmina-AC** [comment]
Thanks for the guidance. I looked through the links to the code and saw that there was already data structures to contain the GPS coordinates. So, before getting deeper into the code I thought of a simpler solution to pass the GPS positions by adding the GPS info to the EXIF of the images. 

By looking at the reconstruction, it seems that it worked. The cameras are shown in reasonable positions and all looking to the centre and down. The images I have were taken from a drone going round an object, so that makes sense. Now, I have the rotation matrices and translation vectors for each camera (I get these by converting the Theia reconstruction to a bundler file). As I understand it these matrices are with respect to the first camera (view) considered. 

I'd like to have the rotation matrices with respect to the East North Up coordinate system in order to get the yaw, pitch and roll of the drone for each view. Could you help me on how to achieve this?  

Thanks again.

**Comment by sweeneychris** [comment]
Yes, you are correct that the computed orientations are w.r.t. the first camera and so they need to be "aligned" into the East North Up coordinate system so that they are in the same coordinate system as the GPS positions! To be clear: your orientations and positions are actually in different coordinate systems right now, and these two can be aligned with a single rotation applied to the computed camera orientations. Does that make sense?

Do you have relative poses for pairs of cameras? It seems like you must if you are computing the rotations globally. If so, I would directly use the relative translation constraint to solve for the rotation that will align your two coordinate systems. Typically for [relative pose](http://theia-sfm.org/sfm.html#equation-position_constraint), we have the constraint:

R_i * (c_j - c_i) / ||c_j - c_i|| = t_ij

where R_i is the orientation of camera i, c is the camera positions, and t_ij is the relative translation between the cameras. If you know the camera positions already and want to find the single rotation that you can apply to *all* camera orientations such that everything is in East North Up, your relative pose constraint becomes:

R_align * R_i * (c_j - c_i) / ||c_j - c_i|| = t_ij

The only unknown value here is R_align. You can use this constraint to create an A * R_align = b style linear system (using each known relative pose in your reconstruction) and solve for R_align that minimizes the least squares solution to this linear system.

Let me know if this doesn't make sense. I'd be happy to do a video chat to help explain some of this since it might be a bit hard to explain via GitHub

**Comment by Yasmina-AC** [comment]
Thanks for the detailed explanation. I think I understood it, at least partially. In fact, I think the solution I got working is the option you explained as solving for R_align, though I did it in a "grandma's way" as I'd say in my native language :-).

Let me explain how I got to get a single rotation that can be apply to all the cameras so everything is in East North Up.

1. From the Bundler-style output file I identify the origin camera by its translation vector being close to or exactly (0, 0, 0). If I'm not wrong, all _t_ vectors from all other cameras point to this origin in the local axis system of each camera. To rotate them into a common frame, each camera's _t_-vector is multiplied by the camera's _R_ transpose.

2. I find the corresponding vectors in the world frame (local East, North, Up) from the known GPS positions of each camera.

3. I use an iterative process that seeks to maximise the dot product of the two sets of vectors by further rotating the _t_ vectors (as a unit) until the two sets coincide. The rotation resulting from this process is then applied to each of the R matrices to get each camera's rotation in world axes (East North Up), and hence the camera's yaw, pitch and roll angles .

This seems to work reasonably well, but the resulting angles are typically inaccurate by about +/-1 degree in each axis. The original data produced by Theia is surely more accurate than this. Is there anything wrong with my logic? Otherwise, I should keep debugging my code.

PS: Thanks for offering doing a video chat, for now I think I need to understand a bit better all the concepts involved otherwise I'd probably end up asking too basic questions.

**Comment by sweeneychris** [comment]
Yes, your way does seem fairly similar and probably gives similar results. When you say that angles are inaccurate by +/- 1 degree do you have ground truth to compare it to? Typically Theia's global sfm solvers are slightly more accurate than that for 1dsfm datasets, but that's in the right ballpark.
