### ISSUE TITLE
Add grid based matching to replace Lowes Ratio

### ISSUE THREAD

**Issue by sweeneychris** [sweeneychris/TheiaSfM#179]
https://github.com/JiawangBian/GMS-Feature-Matcher

**Comment by pmoulon** [comment]
Be careful that this will work only if you have a high density of features ;-)

**Comment by sweeneychris** [comment]
@pmoulon I was intending to make it optional. As noted in the paper, it seems to work best for video sequences. Have you tried it? Any comments on performance?

**Comment by pmoulon** [comment]
I tried it and already plan to add it to OpenMVG as a optional filter.

I found that the default threshold is too permissive and so for 3D reconstruction, SLAM related I would like to encourage to use a higher threshold in order to have less false positive matches.

I found some minor bug in the original code. I need to find some time to make a PR to the main repo one day.

**Comment by AIBluefisher** [comment]
I have tried GMS-Matcher with some other approaches to filter wrong matches. But I can't tell more detail for the submission of my paper has not done yet 😂
