### ISSUE TITLE
"Insufficient view pairs to perform estimation."

### ISSUE THREAD

**Issue by kevin0932** [sweeneychris/TheiaSfM#188]
Hi @sweeneychris , thanks for sharing this amazing modular framework.

I tried to use the default Global SfM setup with a given match file and met with the following error "Insufficient view pairs to perform estimation.". Apart from increasing the number of matches in my match file, can you share some experience on which parameters/thresholds I should adjust to increase the the view pairs?
"""
```
I1122 23:38:26.792034 12489 track_builder.cc:125] 704430 tracks were created. 629399 features were dropped because they formed inconsistent tracks, and 25513 features were dropped bec
ause they did not have enough observations.
I1122 23:38:27.728546 12489 reconstruction_builder.cc:357] Attempting to reconstruct 128 images from 2760 two view matches.
I1122 23:38:27.728602 12489 global_reconstruction_estimator.cc:152] Filtering the intial view graph.
I1122 23:38:27.730634 12489 global_reconstruction_estimator.cc:155] Insufficient view pairs to perform estimation.
F1122 23:38:27.730645 12489 build_reconstruction.cc:477] Check failed: reconstruction_builder.BuildReconstruction(&reconstructions) Could not create a reconstruction.
```
"""

Also, I am a little confused, is the preset twoviewinfo input (relative poses R, t) of matches essential for the input match file and beneficial to the reconstruction? If not provided, they can be estimated with Theia framework from the provided feature correspondences?

Thanks a lot for your time and help!

**Comment by sweeneychris** [comment]
Hey, sorry for not seeing this sooner!

> Also, I am a little confused, is the preset twoviewinfo input (relative poses R, t) of matches essential for the input match file and beneficial to the reconstruction? 
Yes, this is part of the data structure saved in the match file. The reconstruction uses these relative poses to estimate the final pose parameters.

>If not provided, they can be estimated with Theia framework from the provided feature correspondences?
Yes! Just run the build_reconstruction application without passing in a match file and it will automatically extract SIFT features and perform feature matching, track creation, and relative pose estimation. You can save this result as a new match file so that you don't have to regenerate matches from scratch later.

If you run into errors like this I would recommend running the application again with verbose logging by adding --v=2 to the command line. This will log additional information that might help diagnose why your reconstruction is failing.
