### ISSUE TITLE
glog dependency not maintainable for Visual Studio

### ISSUE THREAD

**Issue by bvanevery** [sweeneychris/TheiaSfM#24]
I'm using Windows.  I'm stuck at the portion of the CMake build that looks for glog.  glog does not look at all easy to get working on Windows.  Its github repository looks like a mostly dead project with some occasional maintenance done on it.  There is no CMake build, it is Autoconf based, which is problematic for the Visual Studio I'm using.  There's a directory for Windows .sln files but they're 7 years old.  I didn't even try to fire them up, I have no confidence in the headaches that will ensue.  Comment files talk about "initial support" for Windows ala 2008.  That work appears abandoned.

I'm wondering if this is an imported dependency from the Ceres Solver project.  glog is not actually needed to build Ceres Solver.  One can instead select a "mini glog" that Ceres itself rolls up and is maintained.  Does Theia actually need any kind of glog, or is it just trying to make Ceres happy?  If Theia does need glog-like functionality, can it do what Ceres does and use their "mini glog" ?

**Comment by sweeneychris** [comment]
Glog is required and used heavily in Theia. Ceres uses the mini-glog only because Android is not compatible with Glog. Glog does work for windows in general though. Mini Glog is a huge mess and a massive pain (I have talked to the Ceres owners about this) and I do not want to add that to Theia since we do not support Android.

I'm closing this issue since this is not a Theia issue, but an issue for the Glog project.
