### ISSUE TITLE
Triangulation

### ISSUE THREAD

**Issue by inspirit** [sweeneychris/TheiaSfM#29]
I recently came across pretty simple point triangulation method that is fast but not that accurate,
i wonder how does it compare to the ones implemented in Theia:
```
/// R|t is relative transform between [ref]erence and [cur]rent
/// normalised features
bool triangulatePoint(const Eigen::Matrix3d& R,
                      const Eigen::Vector3d& t,
                      const Eigen::Vector3d& ref,
                      const Eigen::Vector3d& cur,
                      Eigen::Vector3d* result)
{

  Eigen::Matrix<double,3,2> A;
  Eigen::Matrix2d ATA, ATAInv;
  Eigen::Vector3d c;
  Eigen::Vector2d d;

  //  both vectors in frame 1
  const Eigen::Vector3d& v1 = ref;
  const Eigen::Vector3d& v2 = R.transpose() * cur;
  //  calculate depths along rays
  A << v1, -v2;
  c = -(R.transpose() * t);
  ATA = A.transpose() * A;

  bool invertible;
  ATA.computeInverseWithCheck(ATAInv, invertible);
  if (!invertible) {
    return false;
  } else {
    d = ATAInv * A.transpose() * c;
    if (d[0] > 0 && d[1] > 0) {
      //  average both points for solution
      *result = ((d[0]*v1 + d[1]*v2 + c)*0.5);
      return true;
    }
  }
  return false;
}
```

**Comment by sweeneychris** [comment]
This seems to be a sort of midpoint method. I have an n-view midpoint triangulation implemented (as well as n-view DLT). The midpoint method is not necessarily very accurate, however, I *always* perform bundle adjustment on the triangulated 3D point (holding cameras constant) after triangulation. I've found that triangulating this way gives very good results on nearly all cases, and the midpoint method is fast. Another issue with this method is that it does not utilize homogeneous vector parameterization. This may lead to ill-conditioned estimations, especially as the 3D point is farther away.

I have an L2-optimal, very fast 2-view triangulation method here: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/triangulation/triangulation.h#L52  There is no need for BA after using that method, since it guarantees optimality. That method should perform much better than the one you've copy/pasted.

**Comment by inspirit** [comment]
in my case test case i have features that are normalized with camera intrinsics:
```
/// assuming we dont have distortion parameters
Eigen::Vector3d xyz;
xyz[0] = (u - _cx)/_fx;
xyz[1] = (v - _cy)/_fy;
xyz[2] = 1.0;
Eigen::Vector3d feature = xyz.normalized();
```
this feature points i use during the whole process of Essential estimation and triangulation.
where methods need 2D input i simply project my features:
```
Eigen::Vector3d feature2d = feature.head<2>() / feature[2];
```
does it work with Theia methods?

**Comment by sweeneychris** [comment]
If you only have normalized features, use the midpoint algorithm: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/triangulation/triangulation.h#L61

That algorithm expects unit-norm rays that must be rotated into a common frame of reference. That is, for each feature you must rotate it according to that feature's camera pose. The ray origins would be the camera positions then.

**Comment by inspirit** [comment]
thanx for explaining. i was using Theia ```Triangulate``` until now. was just wondering about characteristics.

**Comment by sweeneychris** [comment]
Gotcha. Always glad to help answer questions so you can better understand. Hopefully you're finding Theia useful!
