### ISSUE TITLE
cosine distance issue

### ISSUE THREAD

**Issue by inspirit** [sweeneychris/TheiaSfM#39]
seems to be an error here:
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/extract_maximally_parallel_rigid_subgraph.cc#L95

you writing the same values in the loop...

**Comment by sweeneychris** [comment]
Wow, what a silly typo. Surprisingly, it still worked well on every 1DSfM (internet photo collections) dataset I tried! I guess that is because it is very unlikely that the null spaces are only parallel in one direction and not in others.

This should fix it: https://review.gerrithub.io/#/c/250549/

Thanks for the bug report!
