### ISSUE TITLE
Zero mean normalization different for each image in CascadeHasher

### ISSUE THREAD

**Issue by paulinus** [sweeneychris/TheiaSfM#49]
In `CascadeHasher`, when computing hash codes for an image, the descriptors are first modified by subtracting the mean descriptor of that image.

This is done for each image independently. Thus, the same descriptor in different images may end up having different hash codes, because the mean descriptor may be different on each image.

Should there be a global `mean_descriptor` so that all images use the same?

**Comment by sweeneychris** [comment]
You are correct that, according to the paper, there should be a global `mean_descriptor` that normalizes the descriptors across all of the images. However, @pmoulon did some quick experiments (in an offline discussion) that showed that have a `mean_descriptor` per image vs a global `mean_descriptor` did change the performance very much. 

Having a local `mean_descriptor` significantly simplifies the computation for matching, since you can create the hashed descriptors for each image independently and as soon as they are added to the `FeatureMatcher`. If you use a global `mean_descriptor` then you need to make a pass over all of the features to compute the global `mean_descriptor` before creating any of the hashed descriptors, so it adds a lot of computation load.

**Comment by paulinus** [comment]
Thanks for your answer! good to know that it works using different means. I wouldn't have bet on it.

If there was a need for a global mean and computation load was a problem, there is also the solution of using the mean descriptor of the first image to normalize all the other, or even to hard code a generic mean descriptor. But if using different means works, that is simpler.
