### ISSUE TITLE
Allow any combination of intrinsics to optimize and bounds on values.

### ISSUE THREAD

**Issue by MikeUnverferth** [sweeneychris/TheiaSfM#51]
Often focal length is available from Exif, and principal point will be near, though not precisely at, the center of the image. It would be useful to be able to limit ranges for focal length and principal point deviation from priors, or use fixed focal length while still optimizing principal point and radial distortion. At least allowing all combinations seems like it would be straightforward using enum values for OptimizeIntrinsicsType that can be bitwise-or'd together.

Since Ceres allows for setting lower and upper bounds on problem parameters allowing these to be specified seems straightforward also. These might be specified as maximum deviation value, or perhaps a percentage of the IntrinsicsPrior value?

**Comment by sweeneychris** [comment]
Thanks for the interest in the library. I'm open to a new way to specify which camera intrinsics should be optimized. If you have a good solution, could you submit a patch?

As for setting upper and lower bounds, I generally have tried to stay away from adding hard bounds like that because users will have so many different types of cameras and so the bounds will have to be very wide. I think specifying a maximum percentage of the IntrinsicsPrior value is a good idea! Could you submit a patch for that as well?

**Comment by sweeneychris** [comment]
With this commit you can now optimize any type of camera intrinsics using bitwise masks. Thanks for the idea! Sorry it took a while to implement correctly...

https://github.com/sweeneychris/TheiaSfM/commit/80498093d1e3f0b3913d37ed68f8afa2979af3c6
