### ISSUE TITLE
global sfm is creating disconnected reconstructions into one

### ISSUE THREAD

**Issue by avanindra** [sweeneychris/TheiaSfM#61]
Hello,

I have been testing theia for past few days and many times  I notice that the output reconstruction has disconnected set of multiple reconstructions , with their own scales. I want to separate these reconstructions , and ideally i think it should not happen. How can I fix this?....

**Comment by sweeneychris** [comment]
Just to be clear, you are getting a single reconstruction that contains multiple 3D models within it?

Theia, like all other SfM libraries, utilizes 2-view matching to determine which images view overlapping parts of the scenes and to determine 3D tracks (i.e., which images observe which 3D points). So images will only be "connected" to each other if they have been successfully matched previously. I would be surprised if there were multiple disconnected 3D models showing up in a single reconstruction.

It is more likely that you are attempting to reconstruct a scene with weak connectivity. By that I mean you have several areas in the scene that are densely connected and can be reconstructed well; however, the "links" connecting these dense regions are weak, so the final reconstruction cannot properly determine the right geometric relationship between the dense regions.

As suggested in your other issue, I would make the filtering more strict (and/or enable the extraction of hte maximum parallel rigid subgraph). You can also try altering the bundle adjustment filtering. After BA is run, 3D tracks with bad reprojection errors are removed -- you can alter the threshold at which the tracks are removed (higher is a "looser" threshold, lower is more strict)

**Comment by avanindra** [comment]
Yes , sometime I am getting multiple 3d models in one reconstructions. And you are right , in such cases  , there are weak connections between sets of photographs. The problem is , once i get such reconstructions , I can not feed them into any further pipelines , that's why I wanted to filter out smaller models ( with fewer cameras ) from the total reconstruction and keep the largest connected component. Though I am trying the settings you mentioned , if I face any problem I would report.

Thanks for the reply.

**Comment by sweeneychris** [comment]
Incremental SfM is almost always better for weakly connected scenes. You can try to fix this in one of a few ways: 

1) "loosen" the matching criterion for 2-view matches so that more 2-view matches get through the matching stage. This would possibly add some connectivity in the areas that have weak connectivity now so that you can get a single nice reconstruction 

2) Adjust the SfM filters to be more strict so that the model is broken up.

3) Utilize the [normalized graph cuts algorithm](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/math/graph/normalized_graph_cut.h) to split the scene into several parts before estimating SfM. Then run SfM on each of the subgraphs that you found.

**Comment by sweeneychris** [comment]
there are of course more options, but those might be the most sensible/straighforward ones

**Comment by sweeneychris** [comment]
Can we close the issue if this is solved?

**Comment by avanindra** [comment]
Yes we can close this issue. Thanks for the answers.
