### ISSUE TITLE
Fit plane with orthogonal distance regression

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#78]
I was wondering if it will be useful to implement this in theia.

There is an estimator to find a plane in a set of points with sample consensus.
It can be used for example as a final step to refine the solution of the estimator on the inliers.

**Comment by sweeneychris** [comment]
The main reason that I have not included a linear regression is because I found that point-to-plane distance (which is the error term for these sorts of solvers) is meaningless in SfM due to the fact that the scene scale is arbitrary. This is why I highly recommended using LMeds for finding a dominant plane since it does not require a threshold.

So I am not opposed to having this in the library (and will welcome a patch if you'd like to implement it) but the users of this function should be aware of its limitations
