### ISSUE TITLE
surface of point cloud appears a curve

### ISSUE THREAD

**Issue by jakexie** [sweeneychris/TheiaSfM#92]
When i use TheiaSFM to deal with a large scale scene, the result of "build_reconstruction" appears a curve . 
![screenshot from 2016-06-29 17 11 17](https://cloud.githubusercontent.com/assets/17716347/16446941/c099b896-3e1c-11e6-9453-a2ac5b41a470.png)
  But when i use opemvg library to solve the same images, i got the result like following:
![screenshot from 2016-06-29 17 12 08](https://cloud.githubusercontent.com/assets/17716347/16447004/ec980fa6-3e1c-11e6-8dae-a916feac6a03.png)
  It is obvious that the result of openmvg library has a smaller curve.
  I don't know the what factors led to this result. how can i do to reduce the curve of reconstruction result of theiasfm?

**Comment by pmoulon** [comment]
Here my idea on it:
This is a well known problem when distortion & motion compensate each other.
FYI: See Changchang Wu, "Critical Configurations for Radial Distortion Self- Calibration", CVPR 2014.
See here for more info: https://github.com/openMVG/openMVG/issues/524#issuecomment-209835274

Classic solution is to use know distortion factor as input to compute better relative pose estimates, or to use a two height flight path in order to help the BA with more convergent rays that are not subject to local minima.

In OpenMVG the curves tends to be smaller since AC-Ransac is used. AC-Ransac compute dynamic threshold for robust model estimation and so tends to keep more point and so to enhance the SfM results.

**Comment by caomw** [comment]
good

**Comment by sweeneychris** [comment]
I think Pierre's assessment is mostly correct. I will say, though, that it is hard to state why OpenMVG performs more reasonable than Theia because the input matches, tracks, etc. may be different. It could certainly be the case that OpenMVG is doing a better job of computing 2-view matches than Theia for this case, which is leading to a more constrained reconstruction.

I would also suggest using a robust cost function like Huber or Cauchy for Theia. Or, if you know that your flight pattern is roughly on a plane then you can add an extra term to the bundle adjustment so that the altitude (z-values) are all roughly equal.

**Comment by jakexie** [comment]
thank for your answers @sweeneychris @pmoulon
