### ISSUE TITLE
A small bug in feature_matcher.cc:148

### ISSUE THREAD

**Issue by mhsung** [sweeneychris/TheiaSfM#97]
Hi Chris,

I found a small bug in feature_matcher.cc:
Line 148: CHECK_EQ(image_names_.size(), intrinsics.size());

It should be:
CHECK_EQ(image_names.size(), intrinsics.size());
without '_' after 'image_names'.

**Comment by mhsung** [comment]
Also I think this should be added in 'match_features.cc:SetMatchingOptions()' function:

  matching_options->geometric_verification_options.min_num_inlier_matches =
      FLAGS_min_num_inliers_for_valid_match;

**Comment by sweeneychris** [comment]
Thanks for the bug report. The first one has now been fixed here: https://github.com/sweeneychris/TheiaSfM/commit/41909289a7f94a6bb4195f8ca889268023dba12d

As for the match_features.cc code, this module no longer exists in the master repo. This is because feature files do not contain camera information (like CameraIntrinsicsPriors) and so two-view geometry cannot be accurately estimated because parameters like principal point cannot be set.

**Comment by mhsung** [comment]
Could you explain a little bit more detail about the problem in match_features.cc? I thought that the function 'ReadIntrinsicsFromCalibrationFile()' reads all camera information from the calibration file. Is there any extra information not included in the calibration file?

**Comment by sweeneychris** [comment]
Match Features can *optionally* read in calibration, but was not required. I think the combination of optional and required files in that program made for a confusing interface so I removed it. I will try to upload code so that feature extraction is skipped in cases where the feature files are present, so you will effectively be able to run build_reconstruction and other code to redo the matching without having to re-extract features every time.
